### ISSUE TITLE
full-width="full-width" not working for section or wrapper

### ISSUE THREAD

**Issue by TechBill** [artf/grapesjs-mjml#268] opened 2021-12-01 17:43 UTC
The attribute full-width doesn't seem to work for wrapper and section mjml components.   

MJML try it live show it to be part of the attribute for section and wrapper 

https://mjml.io/try-it-live/components/section

**Comment by ronaldohoch** [comment] 2022-09-02 17:38
@TechBill, have you discovered anything?

**Comment by TechBill** [comment] 2022-09-02 18:26
@ronaldohoch It works just that editor doesn't render it probably. 

We have to add it in then send a test email to ourselves or convert to HTML to confirm that it's working.

**Comment by ronaldohoch** [comment] 2022-09-22 14:48
@DRoet can you help us with it?

**Comment by ronaldohoch** [comment] 2022-09-23 17:38
WE DID IT!!
Asap we will open a PR to it!
https://www.loom.com/share/be13b096764045099b9b8fcdedd9b34c

**Comment by lechuhuuha** [comment] 2022-12-02 04:12
> WE DID IT!! Asap we will open a PR to it! https://www.loom.com/share/be13b096764045099b9b8fcdedd9b34c

hi any update on PR. The editor still not render corretly althogh send mail work

**Comment by TechBill** [comment] 2022-12-02 13:50
Been a year since I reported it .... I would be interested in the update as well too

**Comment by gustavohleal** [comment] 2022-12-02 14:12
Oh yeah... I solved with @ronaldohoch  and was going to open the PR but forgot. Sorry guys. Will do it this afternoon (in brazilian time)

**Comment by lechuhuuha** [comment] 2022-12-02 15:11
> Oh yeah... I solved with @ronaldohoch and was going to open the PR but forgot. Sorry guys. Will do it this afternoon (in brazilian time)

thanks man its would help us a lot

**Comment by gustavohleal** [comment] 2022-12-02 17:43
Just opened the PR. I would like to advise that this make the section and wrapper elements full width when selected. But is just the selection, the content and background still going to respect the 600px width limit when full-width is not selected. Once its selected than the background color or image will extend to the whole canvas.
The problem was that when full-width is added the MJML engine would change the structure of the elements and the function `getChildrenContainer()`from grapes components would return the wrong query to get the childrens container. But also mj-body element add a div with max-width, so i removed this max-width when the body is rendered.

**Comment by lechuhuuha** [comment] 2022-12-02 18:56
> Just opened the PR. I would like to advise that this make the section and wrapper elements full width when selected. But is just the selection, the content and background still going to respect the 600px width limit when full-width is not selected. Once its selected than the background color or image will extend to the whole canvas. The problem was that when full-width is added the MJML engine would change the structure of the elements and the function `getChildrenContainer()`from grapes components would return the wrong query to get the childrens container. But also mj-body element add a div with max-width, so i removed this max-width when the body is rendered.

thanks you very much for the fix. Mind if i ask one more question. Have you face this issues in this [link](https://github.com/artf/grapesjs-mjml/issues/125) some time i see the attribute added in style manager or trait manager and  then the editor just strip out attribute or not render correctly

**Comment by DRoet** [comment] 2022-12-05 15:12
Fixed in v1.0.3

**Closed by DRoet** 2022-12-05 15:12 UTC

**Comment by lechuhuuha** [comment] 2022-12-13 10:17
> Just opened the PR. I would like to advise that this make the section and wrapper elements full width when selected. But is just the selection, the content and background still going to respect the 600px width limit when full-width is not selected. Once its selected than the background color or image will extend to the whole canvas. The problem was that when full-width is added the MJML engine would change the structure of the elements and the function `getChildrenContainer()`from grapes components would return the wrong query to get the childrens container. But also mj-body element add a div with max-width, so i removed this max-width when the body is rendered.

Hello. I see other bug is when you set backgroud-image on component wrapper and then set full-width on wrapper the editor did not render correctly
You can test on the lastest version of this repo to see the bug

Expected behavior : 
![image](https://user-images.githubusercontent.com/59781669/207290786-b0928569-4344-4436-9124-4af1e6594aa6.png)

The result: 
![image](https://user-images.githubusercontent.com/59781669/207290903-afa04bfc-82bc-47dc-b2d7-de45b025a176.png)

Did you encounter this issue before ?

Thanks

**Comment by lechuhuuha** [comment] 2022-12-13 16:41
> > Just opened the PR. I would like to advise that this make the section and wrapper elements full width when selected. But is just the selection, the content and background still going to respect the 600px width limit when full-width is not selected. Once its selected than the background color or image will extend to the whole canvas. The problem was that when full-width is added the MJML engine would change the structure of the elements and the function `getChildrenContainer()`from grapes components would return the wrong query to get the childrens container. But also mj-body element add a div with max-width, so i removed this max-width when the body is rendered.
> 
> Hello. I see other bug is when you set backgroud-image on component wrapper and then set full-width on wrapper the editor did not render correctly You can test on the lastest version of this repo to see the bug
> 
> Expected behavior : ![image](https://user-images.githubusercontent.com/59781669/207290786-b0928569-4344-4436-9124-4af1e6594aa6.png)
> 
> The result: ![image](https://user-images.githubusercontent.com/59781669/207290903-afa04bfc-82bc-47dc-b2d7-de45b025a176.png)
> 
> Did you encounter this issue before ?
> 
> Thanks

Ok i manage to find where its got wrong

When you use full-width with background-url mjml will render another div so the children selector not get its right
Change Wrapper.ts from this
```
      getChildrenSelector() {
        if (this.model.getAttributes()['full-width']) {
          return 'table > tbody > tr > td > div > table > tbody > tr > td';
        } else
          return 'table > tbody > tr > td';
      },
```

To this

```
      getChildrenSelector() {
        if (this.model.getAttributes()['full-width'] && this.model.getAttributes()['background-url']) {
          return 'table > tbody > tr > td > div > div > table > tbody > tr > td';
        } else if (this.model.getAttributes()['full-width']) {
          return 'table > tbody > tr > td > div > table > tbody > tr > td';

        }
        else
          return 'table > tbody > tr > td';
      },
```

So the editor will render correctly
![image](https://user-images.githubusercontent.com/59781669/207391969-c5369899-4a34-4c11-85d4-15fc59642746.png)

So far i dont see any side effect

Hope this help someone.

**Comment by DRoet** [comment] 2022-12-13 18:59
@lechuhuuha feel free to open a PR so I can merge the fix
