### ISSUE TITLE
[0.1.8] Demo not working

### ISSUE THREAD

**Issue by FlyveHest** [artf/grapesjs-mjml#112] opened 2019-07-25 11:44 UTC
We have a completely fresh install of 0.1.8 and get the following error in console upon loading index.html

```
grapesjs-mjml.min.js:2 Uncaught TypeError: Cannot read property 'innerHTML' of null
    at child.getTemplateFromEl (grapesjs-mjml.min.js:2)
    at child.getTemplateFromMjml (grapesjs-mjml.min.js:2)
    at child.render (grapesjs-mjml.min.js:2)
    at child.addToCollection (grapes.js:36452)
    at grapes.js:36497
    at Function../node_modules/underscore/underscore.js._.each._.forEach (grapes.js:20697)
    at child.each (grapes.js:4459)
    at child.render (grapes.js:36496)
    at child.renderChildren (grapes.js:36286)
    at child.render (grapes.js:36301)
```

It looks like it could be the same issue in #110 that is still in 0.1.8

**Comment by artf** [comment] 2019-08-12 23:05
Duplicate of #110

**Closed by artf** 2019-08-12 23:05 UTC
Labels: duplicate
