### ISSUE TITLE
[BUG] Can't add columns in version 0.0.24

### ISSUE THREAD

**Issue by StephanHovius** [artf/grapesjs-mjml#21] opened 2017-11-07 10:03 UTC
This is also not working the online demo:

When I try to add a column or double column, the editor gives a warning / error message:

"Invalid target position: Target collection not found, Target is not droppable, accepts [undefined], Component not draggable, acceptable by [undefined]"

![image](https://user-images.githubusercontent.com/32666012/32487856-23dfe0aa-c3ab-11e7-8618-c3521eccf550.png)

Kind regards,

Stephan Hovius

**Comment by StephanHovius** [comment] 2017-11-07 16:10
I have a fix for this problem, so maybe we can update it soon?

the problem is solved bij changing in components.js row 370:
`draggable: '[data-type=mj-container]'`
to 
`draggable: true,`

in the domc.addType('mj-section' --> model -->  defaults

**Comment by artf** [comment] 2017-11-08 12:28
it's more like a workaround rather than a fix, but as I don't have time to investigate more on it I'll accept a PR

**Comment by mathieuk** [comment] 2017-11-09 05:41
@artf I've looked into this, this seems to happen because for the mjml plugin the actual HTML gets generated at coreMjmlView::getTemplateFromMjml()  (https://github.com/artf/grapesjs-mjml/blob/master/src/components.js#L161) and assigned to the `sandboxEl`. But this `sandboxEl` is created and then not inserted into the DOM meaning it has no parentNode (https://github.com/artf/grapesjs-mjml/blob/master/src/components.js#L20). This breaks the draggable/droppable filtering in use by this plugin because the Sorter _expects_ a parentNode  or falls back to the body of the document that created the element (https://github.com/artf/grapesjs/blob/dev/src/utils/Sorter.js#L178) . Where it won't find it since it's not inserted in the DOM. 

So seems to me either the sandboxEl needs to be inserted into the DOM so it can be found by the `querySelectorAll()` calls done by `Sorter::matches()` or that same method needs to create a parentNode for the element it's looking for instead of falling back to the body. A sample implementation in Grapesjs' Sorter.js::matches() would be: 

```
  matches(el, selector, useBody, debug=false) {
    var startEl;

    // if we don't have a parentNode, create a node so the 
    // querySelectorAll() call below can find something. 
    if (!el.parentNode) {
        startEl = document.createElement('div');
        startEl.appendChild(el);
    } else {
        startEl = el.parentNode;
    }

    //startEl = useBody ? startEl.ownerDocument.body : startEl;
    var els = startEl.querySelectorAll(selector);
    var i = 0;
    while (els[i] && els[i] !== el)
      ++i;
    return !!els[i];
  }
```

Would you take that as a PR too ?

**Comment by artf** [comment] 2017-11-09 20:17
Thanks @mathieuk, it was actually an issue with `matches` in Sorter. It was affecting also other stuff inside the core. Now should be fixed, can you confirm?

**Comment by mathieuk** [comment] 2017-11-10 05:51
Confirmed fixed.

**Closed** 2017-11-10 13:18 UTC
