### ISSUE TITLE
dragging additional social element not working

### ISSUE THREAD

**Issue by rcloss** [artf/grapesjs-mjml#242] opened 2021-04-20 18:47 UTC
I've confirmed this is happening in the demo also, but if you add a Social Group block the first time you add a social element it doesn't display, but as soon as you drag elements around it appears and it also appears if you save the template and come back.

If you add a second one it displays just fine, not sure what the issue is

**Comment by rcloss** [comment] 2021-04-22 16:07
It appears the same issue is happening with NavBar and NavBarLink

**Comment by slipperyfrank** [comment] 2021-06-15 16:34
I've noticed the same behaviour when duplicating columns, navbar links, social elements.

**Comment by slipperyfrank** [comment] 2021-06-18 15:33
Duplicate of #182

**Comment by artf** [comment] 2022-10-01 12:20
Closing this one as it should be already fixed

**Closed by artf** 2022-10-01 12:20 UTC
