### ISSUE TITLE
Text element below image not rendering in editor

### ISSUE THREAD

**Issue by digitalgym** [artf/grapesjs-mjml#157] opened 2019-12-01 01:40 UTC
When I load the below into the editor the text element below the image does not render, I can see the element in code view but it does not appear in the editor. Removing the image fixes the issue so it appears the text element can not be placed directly after an image element, is this expected behaviour?

`<mj-section>
      <mj-column>
        <mj-text>Insert text here
        </mj-text>
        <mj-image src="http://placehold.it/350x250/78c5d6/fff"/>
        <mj-text>Content 1
        </mj-text>
      </mj-column>
    </mj-section>`

**Comment by navewi** [comment] 2019-12-03 12:41
Yes this is a known issue: #149 

If you change your code to that and do the import, it should work properly:
`<mj-section> <mj-column> <mj-text>Insert text here </mj-text> <mj-image src="http://placehold.it/350x250/78c5d6/fff"></mj-image> <mj-text>Content 1 </mj-text> </mj-column> </mj-section>`

A temporary fix for this is mentioned in the above linked issue in one of the comments (set void to false).

**Comment by DRoet** [comment] 2020-07-17 15:06
duplicate of https://github.com/artf/grapesjs-mjml/issues/149

**Closed by DRoet** 2020-07-17 15:06 UTC
