### ISSUE TITLE
Clone doesn't take into account styled attributes

### ISSUE THREAD

**Issue by artf** [artf/grapesjs-mjml#1] opened 2017-06-28 20:06 UTC
https://github.com/artf/grapesjs/issues/129

**Comment by masfi** [comment] 2017-12-20 14:39
Is there any fix for this? I am experiencing this issue as well. It would be fine if the view of the duplicated block didn't show as a complete copy of the original block, styling and all.

**Comment by DRoet** [comment] 2020-07-17 07:08
I can't reproduce this behaviour in the demo or locally, closing this for now

**Closed by DRoet** 2020-07-17 07:08 UTC
