### ISSUE TITLE
Demo does not work on IE11

### ISSUE THREAD

**Issue by tdejong-tools4ever** [artf/grapesjs-mjml#181] opened 2020-05-25 06:10 UTC
Issue: 

When opening [https://grapesjs.com/demo-mjml.html](https://grapesjs.com/demo-mjml.html) in IE11 it should load. Currently it only shows a blank page.

Console output:
![image](https://user-images.githubusercontent.com/54626878/82783598-17681400-9e5f-11ea-9d7e-7d3e45f223a5.png)

**Comment by DRoet** [comment] 2020-07-17 19:22
duplicate of https://github.com/artf/grapesjs-mjml/issues/77

**Closed by DRoet** 2020-07-17 19:22 UTC
