### ISSUE TITLE
social-icons toolbar position issue.

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs-mjml#177] opened 2020-04-20 20:11 UTC
Steps: First we drag a group-social-element then drag a single social-element, it loses the position of component toolbar of remainig social-elements.

**Comment by DRoet** [comment] 2020-07-16 15:22
duplicate of https://github.com/artf/grapesjs-mjml/issues/182

**Closed by DRoet** 2020-07-16 15:22 UTC
