### ISSUE TITLE
MJ-TEXT Content exceeds outside the borders.

### ISSUE THREAD

**Issue by NorthstarTech** [artf/grapesjs-mjml#94] opened 2019-02-13 12:09 UTC
![2019-02-13_17-06-22](https://user-images.githubusercontent.com/33541046/52710713-d7ef1e80-2fb1-11e9-9747-0332f6418dd0.png)

mj-text content exceed outside the  container. Please provide the solution for it. Need help.
Thanks. Image Attached taken from the mjml-demo

**Comment by DRoet** [comment] 2020-07-17 07:13
I can't reproduce this anymore in the latest version. closing for now

**Closed by DRoet** 2020-07-17 07:13 UTC
