### ISSUE TITLE
mj-divider elements are considered as container at import

### ISSUE THREAD

**Issue by pcorpet** [artf/grapesjs-mjml#215] opened 2020-12-06 13:53 UTC
When importing an MJML containing an `mj-divider` with an auto-closing XML tag:
```xml
<mj-section>
  <mj-image ... />
  <mj-divider />
  <mj-text>
    Content
  </mj-text>
</mj-section>
```
the plugin ignores the self-closing tag and includes everything that follows the divider *inside* the divider component which doesn't make sense. The UI hides the content, however when viewing the MJML code, it's still there:
```xml
<mj-section>
  <mj-image ... />
  <mj-divider>
    <mj-text>
      Content
    </mj-text>
  </mj-divider>
</mj-section>
```

I've tried to follow the code, and it seems that it's due to the use of `.innerHTML` and DOM to parse the XML, resulting in considering `mj-divider` as an opening tag which closing tag has been forgotten. A bit like `<br>` in HTML actually means `<br />` in XHTML. However it's the same for `mj-image` and somehow grapejs-mjml fixes it further down the road.

Any idea to help me fix the code?

**Comment by DRoet** [comment] 2020-12-06 14:15
Duplicate of https://github.com/artf/grapesjs-mjml/issues/149.

**Closed by DRoet** 2020-12-06 14:15 UTC

**Comment by pcorpet** [comment] 2020-12-06 22:45
Yep, sorry I didn't search enough in the open issues.
