### ISSUE TITLE
[0.1.15] Cannot read property 'innerHTML' of null in production, works fine in dev

### ISSUE THREAD

**Issue by Ardhimas** [artf/grapesjs-mjml#155] opened 2019-11-18 19:23 UTC
Hello everyone,

First of all, thanks to everyone who has done a great job in this package. Unfortunately, I ran into an issue in prod that doesn't happen in dev.

I did some research on the existing issues and found https://github.com/artf/grapesjs-mjml/issues/110 which had been closed and resolved. However, I ran into the exact same issue. I was able to downgrade `grapesjs-mjml` to version `0.0.31` to get it working as other posters suggested before the fix https://github.com/artf/grapesjs-mjml/pull/115. This confirms that I ran into the same issue, but it seems that the fix did not work for me. I've tried several versions of `grapesjs-mjml` at `0.1.x`, but it seems `0.0.31` is the only one that worked in prod. The issue with this is that the lack of support for `mj-style` tags could cause issues for my use case.

I put together a quick repo to demonstrate the divergent behavior between dev and prod webpack environments here https://github.com/Ardhimas/grapesjs-mjml-broken-demo.

Unfortunately, I am not sufficiently well versed in the intricacies of webpack to suggest what the issue could be. I'd appreciate it if someone could take a look and see what the issue is.

Thanks in advance,

Ardy

**Comment by Felix-Indoing** [comment] 2019-11-21 08:45
Confirm exactly the same issue here.

**Comment by DRoet** [comment] 2019-11-21 11:18
I am not exactly sure what caused the breakage this time, but the problem is that this plugin doesn't work when function names gets distorted by minifiers. This is due to the fact that the plugin calls "parent" methods from `grapesjs` without having a direct dependency

If you are using `terser` there is an [option](https://github.com/terser/terser#minify-options) to keep the original function names: `keep_fnames`

**Comment by MaxTemplar** [comment] 2019-11-28 16:59
i have same issue when use v-html in #gjs container and use fromElement: true. if I set fromElement to false or not use v-html error is not present.

**Comment by jcolla-holla** [comment] 2020-11-30 17:43
Anyone find a consistent solution for this?  With examples ideally that can be shared.

**Comment by DRoet** [comment] 2020-12-01 08:34
Workaround is to import the unminified bundle `import grapesjsMJML from 'grapesjs-mjml/dist/grapesjs-mjml'` but this will bloat up your bundle size quite a bit, I'm hoping a future release (5.x) of mjml will have better browser support since it will exclude things like the minifier/beautifier and will have a significant bundle decrease overall.

**Comment by DRoet** [comment] 2020-12-29 15:58
This should be fixed now as of `v0.4.0` since it include the official `mjml-browser` build

**Closed by DRoet** 2020-12-29 15:58 UTC
Labels: bug
