### ISSUE TITLE
Social Elements not being added visually (just on view-code)

### ISSUE THREAD

**Issue by devguar** [artf/grapesjs-mjml#182] opened 2020-05-29 00:10 UTC
Hi guys,
I'm using GrapesJS MJML and I'm having an issue with social-elements.

Steps:
1. Drag the Group Social do the right place (ok works)
2. It will create 3 icons as default (Facebook, Google, Twitter)
2. Drag a new Social Element at the right side of the Twitter icon (as a fourth element), its not showing this new element anywhere.
3. If you go to the View Code, the element is there. Not showing just visually.
4. If you try again to add the social element on the same position it works. But, it will be saved duplicated (because the element droped at the step 2 still there on the code).

This behavior is happening also on the Demo, here:
https://grapesjs.com/demo-mjml.html

Let me know if I can give you more details about this problem.
Thanks!

**Comment by gobwah** [comment] 2020-12-11 11:50
Hi guys,

I think the problem is similar on "columnizable" element. You can reproduce this issue also with mj-navbar-link.
In the same way, this issue happens when you copy (by using the "copy" button of the selected element toolbar) an element such as mj-social-element, mj-navbar-link or mj-column.

It is like the action is performed but not rendered. Like it was said, the added or copied element is present but not visible. If I save my model (in database) and re-open it (from database) the previously added or copied element is now rendered. Another possible way to render it is to add again the same element (previously mentionned) or delete the current one.

I don't have solution (sorry ^^') but I think the problem is similar for elements I called "columnizable" and may be linked by a common code issue

**Comment by gobwah** [comment] 2020-12-11 15:55
Hi,

I found a temporary solution by using events 'component:add' and 'update'.

- 'component:add' has the component model in parameter, so I check the type and set a global variable to true for later.
- 'update' check if my global variable is true and I use editor.setComponents(editor.getHtml()) to kind of 'refresh' the editor content

`
editor.on('component:add', (component) => {
	// to prevent 'columnizable' default
	switch(component.get('type')) {
	case 'mj-navbar-link':
	case 'mj-social-element':
	case 'mj-column':
		needRefresh = true;
		break;
	default:
		//nothing
	}
});

editor.on('update', () => {
	// to prevent 'columnizable' elements render default
	if(needRefresh) {
		editor.setComponents(editor.getHtml());
		needRefresh = false;
	}
});
`
It seems to work well in my case but don't hesitate to improve it ;)

**Comment by lahdekorpi** [comment] 2020-12-17 15:21
This issue happens with other elements as well. If I clone elements, they appear in one location in the preview but are in a different location in the MJML. Refreshing the components via the same hack as listed by @gobwah puts them in the correct position.  
But doing a full refresh on each "component:add" seems just mad.

**Comment by aakash2610** [comment] 2021-08-30 09:23
I am also facing the same issue, and I am using v0.5.5. Is there any timeline for fixing this issue?

**Comment by yanfanvip** [comment] 2021-12-14 02:45
> Hi,
> 
> I found a temporary solution by using events 'component:add' and 'update'.
> 
> * 'component:add' has the component model in parameter, so I check the type and set a global variable to true for later.
> * 'update' check if my global variable is true and I use editor.setComponents(editor.getHtml()) to kind of 'refresh' the editor content
> 
> ```
> editor.on('component:add', (component) => {
> 	// to prevent 'columnizable' default
> 	switch(component.get('type')) {
> 	case 'mj-navbar-link':
> 	case 'mj-social-element':
> 	case 'mj-column':
> 		needRefresh = true;
> 		break;
> 	default:
> 		//nothing
> 	}
> });
> 
> editor.on('update', () => {
> 	// to prevent 'columnizable' elements render default
> 	if(needRefresh) {
> 		editor.setComponents(editor.getHtml());
> 		needRefresh = false;
> 	}
> });
> ```
> 
> It seems to work well in my case but don't hesitate to improve it ;)


It seems to solve the problem, but it introduces new problems：
drag new column, this can not Undo

**Comment by DRoet** [comment] 2022-02-21 14:40
Should be resolved now that https://github.com/artf/grapesjs-mjml/pull/274 is merged and released in `v0.6.0`

**Closed by DRoet** 2022-02-21 14:40 UTC
Labels: bug
