### ISSUE TITLE
VueJS Production Build - firstChild is null

### ISSUE THREAD

**Issue by lmvdz** [artf/grapesjs-mjml#166] opened 2020-02-04 23:15 UTC
``` 
TypeError: "t.firstChild is null"
    getTemplateFromEl grapesjs-mjml.min.js:34
    getTemplateFromMjml grapesjs-mjml.min.js:34
    render grapesjs-mjml.min.js:34
    addToCollection grapes.min.js:3
    render grapes.min.js:3
    forEach grapes.min.js:2
    a/</t.prototype[i]</< grapes.min.js:2
    render grapes.min.js:3
    renderChildren grapes.min.js:2
    render grapes.min.js:2
    addToCollection grapes.min.js:3
    addTo grapes.min.js:3
    v grapes.min.js:2
    m grapes.min.js:2
    f grapes.min.js:2
    trigger grapes.min.js:2
    _onModelEvent grapes.min.js:2
    v grapes.min.js:2
    m grapes.min.js:2
    f grapes.min.js:2
    trigger grapes.min.js:2
    set grapes.min.js:2
    add grapes.min.js:2
    add grapes.min.js:2
    addComponent grapes.min.js:12
    setComponents grapes.min.js:12
    setComponents grapes.min.js:12
    setComponents grapes.min.js:12
    loadTemplate EmailComposer.vue:115
    documentSelector EmailComposer.vue:70
    VueJS 4
vue.runtime.esm.js:1888:12
    VueJS 7
```

Not sure why I am getting this error, I suspect the mjml imports. 
This only happens when I build for production
Just get a blank, unusable frame.
![image](https://user-images.githubusercontent.com/2179775/73796076-e2ca3280-4771-11ea-90df-6ed7a22a2f12.png)

**Comment by DRoet** [comment] 2020-02-05 15:56
might be similar to issue https://github.com/artf/grapesjs-mjml/issues/155

**Comment by XeonPowder** [comment] 2020-02-05 19:50
Was able to work around this by:

using `<script src="https://unpkg.com/grapesjs-mjml/dist/grapesjs-mjml.min.js"/>` in index.html
instead of ES import.

**Comment by Riley-** [comment] 2020-02-23 18:38
I'm seeing the same issue with Vue (Nuxt) in production, the workaround provided here works (thanks!) but it would be great if we could just import grapes-mjml alongside grapes. I've tried other recommendations, including setting fromElement: false and adding the content to components, which did not work.

**Comment by DRoet** [comment] 2020-03-04 15:59
tried all day debugging this but no luck, very strange that it works when using the CDN

**Comment by DRoet** [comment] 2020-03-05 15:43
Forking the repo and setting `mode: development` in the webpack config solved this issue for me, but increases the bundle size from 1.45mb -> 5mb. So there must be something happening in the minification process that causes this issue :/

**Comment by Ardhimas** [comment] 2020-04-16 16:18
@DRoet I can confirm that was the only reliable solution I found for https://github.com/artf/grapesjs-mjml/issues/155 when I was working through it last year.

**Comment by DRoet** [comment] 2020-07-17 15:08
duplicate of https://github.com/artf/grapesjs-mjml/issues/155

**Closed by DRoet** 2020-07-17 15:08 UTC
Labels: duplicate
