### ISSUE TITLE
Text after an image in same section is missing after import.

### ISSUE THREAD

**Issue by freliberty** [artf/grapesjs-mjml#129] opened 2019-09-16 08:55 UTC
If you drag and drop a text after an image in the same section, the render is ok: 
![Capture d’écran de 2019-09-16 10-51-05](https://user-images.githubusercontent.com/17565667/64945004-f41cac00-d86f-11e9-919a-19ad335fa497.png)

but if you import this code 
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text>I see this text
        </mj-text>
        <mj-image src="http://placehold.it/350x250/78c5d6/fff"/>
        <mj-text>I don't see this text
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

the text "I don't see this text" is missing. see the picture

![Capture d’écran de 2019-09-16 10-30-50](https://user-images.githubusercontent.com/17565667/64945016-f848c980-d86f-11e9-8db0-93b61f144ee3.png)

Thx you

**Comment by navewi** [comment] 2019-09-25 11:38
Hello, did you export the code from the editor you want to import or did you write it by yourself? Because I think you didn't used the image tag right. The Line should be this i guess:

<mj-image src="http://placehold.it/350x250/78c5d6/fff"></mj-image>

So the Text after the Image isn't visible because you didn't close the image tag properly.

**Comment by navewi** [comment] 2019-09-25 13:20
@artf I think this is an issue with the mjml export. 
It exports all images like in the code from freliberty. only in an `<mj-image src=... />` tag without closing it. So everything in the same section / column after the image is not visible, i had the same issue. 
If you change the image-codes in the export-files to `<mj-image src=...>...</image>`  it works again.
Maybe you can fix this.

**Comment by freliberty** [comment] 2019-09-26 12:49
Hi @navewi, @artf 
You have right, if I change my import like` <mj-image src=...></image>` it's OK.
My initial code was genered by the **export module**.

Thanks

**Comment by freliberty** [comment] 2019-11-28 09:37
Hi,
Have you fix this problème?
it's a real big problem for us.
Thank you.

**Comment by navewi** [comment] 2019-11-28 09:43
Hello @freliberty, i set the void property to false. I think this is only a temporary fix, but it works for me right now. The Problem you mentioned here is fixed with this. 

You can look up how to change the void property in this issue: #149 
In one of the comments someone mentioned this. I hope it helps you too.

**Comment by DRoet** [comment] 2020-07-17 15:13
duplicate of https://github.com/artf/grapesjs-mjml/issues/149

**Closed by DRoet** 2020-07-17 15:13 UTC
