### ISSUE TITLE
<mj-image /> not enclosing correctly on visual editor

### ISSUE THREAD

**Issue by Qu4k3** [artf/grapesjs-mjml#279] opened 2022-03-09 22:43 UTC
Hi,
For more than 1 month, and after updating to the latest versions, the problem still persists:
- grapesjs - 0.17.29
- grapesjs-mjml - 0.6.0
- grapesjs-plugin-ckeditor - 0.0.10

I find that when importing a MJML, the texts that follow the images are lost. The <image /> tag is not correctly self closing.

![grapesjs-1](https://user-images.githubusercontent.com/9118664/157550856-087df5bf-5a46-42ab-9c5a-823b4dc86be3.JPG)

The <image> tag is not self-closing and wraps all the text that follows it.

![image](https://user-images.githubusercontent.com/9118664/157549028-68b2bf27-9f4b-4e89-a72e-9356f44d06af.png)

What should be displayed:

![image](https://user-images.githubusercontent.com/9118664/157550932-fdc0fdae-c414-4f2e-be03-eaad44fdba13.png)

The <image> tag is not self-closing and wraps all the text that follows it.

![image](https://user-images.githubusercontent.com/9118664/157549028-68b2bf27-9f4b-4e89-a72e-9356f44d06af.png)

But aparrently, when clicking on export, all the information is correct

![image](https://user-images.githubusercontent.com/9118664/157549363-4da46f1a-7cd1-4624-b73f-40c0e1442baf.png)

![image](https://user-images.githubusercontent.com/9118664/157549176-c831fda7-41de-4752-9fe6-0bd729417c99.png)

**Comment by DRoet** [comment] 2022-03-12 20:21
duplicate of https://github.com/artf/grapesjs-mjml/issues/149

**Closed by DRoet** 2022-03-12 20:21 UTC
