### ISSUE TITLE
Can't add 3rd column more than once

### ISSUE THREAD

**Issue by Geczy** [artf/grapesjs-mjml#37] opened 2017-11-22 20:59 UTC
Weird inconsistencies

http://grapesjs.com/demo-mjml.html

Try dragging `column 3` twice or 3 times into the template

**Comment by artf** [comment] 2017-12-22 00:02
Can't reproduce it Matt, might this be your case https://github.com/artf/grapesjs/issues/595 ?

**Comment by Geczy** [comment] 2017-12-22 00:05
Yeah looks the same. All I do is drag x amount of times and it stops working

**Comment by DRoet** [comment] 2020-07-17 07:05
I can't reproduce this anymore, even in the demo. closing this for now

**Closed by DRoet** 2020-07-17 07:05 UTC
