### ISSUE TITLE
Backbone.UndoManager is not a constructor

### ISSUE THREAD

**Issue by kavikaran** [artf/grapesjs-mjml#16] opened 2017-10-09 13:11 UTC
while loading my grapes-mjml component second time it gives backbone.undomanager error

```
Backbone.UndoManager is not a constructor
    at N.d.initUndoManager (grapes.min.js:17)
    at Object.onLoad (grapes.min.js:15)
    at grapes.min.js:17
    at Array.forEach (<anonymous>)
    at N.d.initialize (grapes.min.js:17)
    at N.d.b.Model (grapes.min.js:2)
    at new N.d (grapes.min.js:3)
    at new b (grapes.min.js:17)
    at Object.init (grapes.min.js:17)
    at VueComponent.mounted (Hello.vue?de18:14)
```

So,
How to destroy grapesjs.init({ })  ??

this is my script code,

```
<script>
let editor = null;
export default {
  name: 'templateEditor',
  mounted () {
  	editor = grapesjs.init({
      height: '100%',
      noticeOnUnload: 0,
      storageManager:{autoload: 0},
      container : '#gjs',
      fromElement: true,
      plugins: ['gjs-mjml'],
      pluginsOpts: {
        'gjs-mjml': {}
      }
    });
    window.editor = editor;
  }
}
</script>
```

**Comment by artf** [comment] 2017-10-10 11:55
Which version of grapesjs do you use?

**Comment by kavikaran** [comment] 2017-10-10 13:08
you mean grapejs or grapjs-mjml ?

**Comment by kavikaran** [comment] 2017-10-10 13:11
i am using grapejs-mjml  "0.0.8"

**Comment by artf** [comment] 2017-10-11 12:36
grapesjs

**Comment by kavikaran** [comment] 2017-10-12 05:29
grapesjs ^0.12.6

**Comment by artf** [comment] 2017-10-12 11:44
Sorry but I can't reproduce, try to recreate it with something like jsfiddle/codesandbox

**Comment by Kav-i** [comment] 2017-11-10 13:13
this issue is resolved in newer version.
So it should be close

**Comment by artf** [comment] 2017-11-10 13:20
@Kav-i thanks for letting me know 👍

**Closed by artf** 2017-11-10 13:20 UTC
